### ISSUE TITLE
react-html-parser ownership

### ISSUE THREAD

**Issue by peternewnham** [hedgedoc/html-to-react#20]
I am the project creator for react-html-parser which I have ignored for the past few years due to lack of time and other priorities. I saw this hard fork mentioned in a PR recently so I was wondering if someone here wanted to take over ownership of that project (including the npm package)?

**Comment by mrdrogdrog** [comment]
Except if any of the other maintainers (@davidmehren @ErikMichelson @DerMolly @InnayTool) has another opinion.

**Comment by mrdrogdrog** [comment]
@peternewnham are you okay with that?

**Comment by peternewnham** [comment]
@mrdrogdrog sorry real life is getting in the way again!

I've had a think and because you've already got this repo which is deployed under a different package and is not an exact fork of my project (as the folder structure is different and it's typescript) it will probably be better if I archive and deprecate react-html-parser and point people to this one instead as it's spiritual successor. That way we don't have to worry about ownership or transferring anything between anyone and it's more obvious that yours is a different thing which may have some differences in behaviour.

How does that sound?

**Comment by mrdrogdrog** [comment]
That's also okay for me. 😊

**Comment by mrdrogdrog** [comment]
I'm gonna close this issue now since it there hasn't been any activity for a long time.

@peternewnham If you still wanna deprecated your repo and link to ours as successor, feel free to do so. :relaxed:
