### ISSUE TITLE
Target attribute of anchor tag in html is not parsed by the package

### ISSUE THREAD

**Issue by priyadarshiniMuthuraman** [hedgedoc/html-to-react#30]
Hi,

The target attribute of anchor tag is not parsed by the package, find below the example:

My json content is as follows:

```
{
"link": "Recycling link <a href=\"https://www.test/recycle\" title=\"recycle\" target=\"_blank\" rel=\"author\">www.brother.co.uk/recycling</a>"
}
```
But the o/p is as follows

`<a rel="author" title="recycle" href="https://www.brother.co.uk/recycling">www.brother.co.uk/recycling</a>`

**Comment by mrdrogdrog** [comment]
Hi,

The lib doesn't remove this attribute. Do you use a HTML sanitizer like `DOMPurify`?

**Comment by priyadarshiniMuthuraman** [comment]
> 

Yup, I use  DOMPurify, I will check by removing it. Am sorry.

**Comment by mrdrogdrog** [comment]
Don't worry. That also happened to me, while developing hedgedoc :sweat_smile:
