### ISSUE TITLE
error Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by romanown** [hedgedoc/html-to-react#39]
ERROR in ./node_modules/domhandler/lib/esm/node.js
Module parse failed: Unexpected token (284:47)
You may need an appropriate loader to handle this file type.
|     else if (isTag(node)) {
|         const children = recursive ? cloneChildren(node.children) : [];
|         const clone = new Element(node.name, { ...node.attribs }, children);
|         children.forEach((child) => (child.parent = clone));
|         if (node.namespace != null) {
 @ ./node_modules/domhandler/lib/esm/index.js 2:0-92 3:0-26
 @ ./node_modules/@hedgedoc/html-to-react/dist/elementTypes/ProcessTagNode.js
 @ ./node_modules/@hedgedoc/html-to-react/dist/convertNodeToReactElement.js
 @ ./node_modules/@hedgedoc/html-to-react/dist/processNodes.js
 @ ./node_modules/@hedgedoc/html-to-react/dist/convertHtmlToReact.js
 @ ./node_modules/@hedgedoc/html-to-react/dist/index.js
 @ ./js/routes/posts/components/PostItemOne.jsx
 @ ./js/app.js

ERROR in ./node_modules/htmlparser2/lib/esm/index.js
Module parse failed: Unexpected token (59:9)
You may need an appropriate loader to handle this file type.
|     return getFeed(parseDOM(feed, options));
| }
| export * as DomUtils from "domutils";
| // Old name for DomHandler
| export { DomHandler as DefaultHandler };
 @ ./node_modules/@hedgedoc/html-to-react/dist/convertHtmlToReact.js 4:22-44
 @ ./node_modules/@hedgedoc/html-to-react/dist/index.js
 @ ./js/routes/posts/components/PostItemOne.jsx
 @ ./js/app.js

"react": "^16.13.1",
"@hedgedoc/html-to-react": "^1.3.0",
"webpack": "^3.8.1",

"name": "domhandler",
    "version": "5.0.3",

 "name": "htmlparser2",
    "version": "8.0.1",

**Comment by mrdrogdrog** [comment]
I have no idea what the problem is, what you expect and what preconditions are met.
Just posting some error messages is not helpful.
