### ISSUE TITLE
Cannot destructure property 'decodeEntities' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by jaxramus** [hedgedoc/html-to-react#60]
I am trying to hydrate a react component via a `#root` element

In my server code I am setting this root div via:

```
<div id="root">${ReactDOMServer.renderToString(<Home hello="world" />)}</div>
```

In my client code I'm trying to hydrate this via:

```
const root = document.getElementById("root")
const component = convertHtmlToReact(root.innerHTML)

ReactDOM.hydrateRoot(root, component)
```

which gives me the following error:

> Uncaught TypeError: Cannot destructure property 'decodeEntities' of 'undefined' as it is undefined.

**Comment by mrdrogdrog** [comment]
I checked the source code and found the reason. I can't fix it right now, but I can offer you a workaround. Use `convertHtmlToReact(root.innerHTML, {})` when calling the function.

**Comment by jaxramus** [comment]
i no longer get an error but hydration doesn't seem to do anything:

```
const root = document.getElementById("root")
const component = convertHtmlToReact(root.innerHTML, {})

ReactDOM.hydrateRoot(root, component)
```

**Comment by mrdrogdrog** [comment]
I fixed the deconstruction error and checked the tests. The html parser is working as intended. :shrug:
